development:
  adapter: postgresql
  encoding: unicode
  database: enroll_development
  pool: 5
  username: enroll
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: enroll_test
  pool: 5
  username: enroll
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: enroll_production
  pool: 5
  username: enroll
  password:
