development: &development
  publishable_key: pk_test_vSOC9sUGEcBMh7kdQ5sjcsdM
  secret_key: sk_test_xlf81Tc7EFDDps6VCBue3N2d

test:
  <<: *development

production: &production
  publishable_key: pk_live_LvegTNyjDtP0kI5ffND2Og2x
  secret_key: sk_live_z3RWQGVvlr2CXQfme0JmCE9J

staging:
  publishable_key: pk_test_vSOC9sUGEcBMh7kdQ5sjcsdM
  secret_key: sk_test_xlf81Tc7EFDDps6VCBue3N2d
