#!/bin/sh

set -e
export CC=gcc

echo "==> Installing gem dependencies..."
bundle check --path vendor/gems 2>&1 > /dev/null || {
  bundle install --path vendor/gems --quiet --without staging:production
}

# make the log directory
mkdir -p log

echo "==> Setting up database..."
bundle exec rake db:create
bundle exec rake db:create RAILS_ENV=test
bundle exec rake db:migrate db:test:prepare

echo "==> Creating seed data..."
bundle exec rake db:seed

echo "==> Workshop Platform is bootstrapped!"
